class Compliment
	attr_reader :message, :image
	MESSAGES = [ "I would like to buy a significant piece of art from you anytime, power girl.",
		"Does Ms. America ride a hog? Why not? You are the fashion equivalent of Texas.",
		"One look at the back of your head and I can tell that you’re a person who likes a clean apartment, a Frette sheet, a haircut from a man who feels the same way. I bet you cook and have the sharpest Japanese knives in all of Vegas.",
		"You understand how to make the light flicker off your lashes, you know how to tilt your head just so. What you haven’t figured out yet, is how to stop scaring and intimidating boys with your look. Fuck ’em. Beauty is forever.",
		"You look just like Corin Nemec, except if at the height of his powers, he had joined some kind of fashion-based military outfit.",
		"You have an Izzy Blow — but non-suicidal — super pretty face vibe. Your look is killing it today. The way I picture you is in Lula magazine, floating on a sea of chiffon and blowing bubbles in a rainstorm. Turbans equal difficult-to-pull-off, but today, and probably usually, you are a queen of awesome.",
		"Your messy hair bodes well for your care-free nature, but don’t overdo it. It’s more than a bit unkempt, and you could definitely use a trim. Having said that, you strike me as articulate and a good guy to go get sloshed with.",
		"You win hottest beard in the room. Dude, we're in Dallas. You think we've slept together, but we haven't. But just so you know, I WOULD totally give in, like totally on the first date. You should call my manager and take me out and let me use your hair products in the morning. Stop being such a total girl, Euroman.",
 		"You are the token brilliant songwriter in this room. Every party like this would not be complete without some proper representation from the music canon.  Are you a lost fan? You seem like it. Do you remember that song, 'You Are My Everything'? I think that's what it's called…anyways. I feel like you have a hit jam under your belt or in some way tied to your name. Good job. Hardly anyone can write even on serious jam in their life.", 
		"Your combed back hair reminds me of the boyfriend from Uncle Buck that John Candy hated ever so much because the guy was some type of art world person through and through. You look like someone that is capable of fitting logic together to figure out how things actually come together. That's the fire you hold over other people.", 
		"Basically you look like you're the 'before' image in a 'She's All That' type movie, where we all go, 'Why the hell does THAT girl need a cheerleader makeover? She clearly got her own awesome thing going on. Leave her alone, Freddie Prinze Jr., she is a rare bird who needs to fly her own way!!'",
		"Your entire look says that you are someone who no only has her shit together but whose very together-ness is vaguely threatening to people around her. You walk in wearing an outfit that is basically at the platonic ideal of coordinated and of-the-moment and those tho've got less steady nerves are concerned their looks start to go places -- it's like an earthquake for those who lack self-assurance. Go easy on the less badass, lady -- they're looking to you for guidance.",
		"You have this whole Lita Ford form the Runaways, coupled with a southern California vibe, also coupled with a Fairuza Balk from the Craft thing going on. You're the kind of girl I'ld like to skip 6th period with, and get into a whole heap of trouble with before my parents were none the wiser.",
		"The black dress says 'elegance in spades' but the gnarly shoulder pads say 'I am ready for the mad max post-apocalypse.' Tina Turner, take a hike, there's a new rule of the Thunderdome right here -- I think it' son coincidence that you came here rocking' a chic look with a little aggression. When it comes to doing battle in the aesthetic war zone, though, you'll never find your equal.",
		"You're a party girl - but you've got a brain. An internal monologue that runs your day. Some think that you have an air of condescension - but you're just right more than you're not.",
 		"You look like an Eastern European assassin…a man that works for the gov and solves problems. But more like you espouse the tall and dark style that New Yorkers are known for. The cigarette just further backs up my idea of you as a hit man. I don’t want to run into you in a dark alley. Style at its best nonetheless.",
 		"Did you need a few drinks to work up the courage to do this? You look a little tanked. That hair, and that deep look you shot me, are dashing. That beard is all right now. Just don’t let it get any longer, unless you wanna start looking homeless.",
		"You look like the aunt that I always wish I had. The one that would have shown me good things to listen to, and would have smoked pot with me for the first time. Maybe in another lifetime."]
 	def initialize
		@message = MESSAGES.sample
		@image = Dir["./public/images/*"].sample[8..-1]
	end
end